#########################开发环境配置#########################
management:
  endpoints:
    web:
      exposure:
        include: "shutdown"
  endpoint:
    shutdown:
      enabled: true
#单数据源配置 start#
spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://119.29.67.61:3306/logistic_dev?useUnicode=true&characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false
      username: root
      password: 1234
  main:
    allow-bean-definition-overriding: true
#单数据源配置 end#
#分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  offsetAsPageNum: true
  supportMethodsArguments: true
#分页
#mybatis-plus配置 start#
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.diyou.entity.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用
  global-config:
    id-type: 5
    field-strategy: 0
    db-column-underline: true
    refresh-mapper: true
    capital-mode: true
    #meta-object-handler: com.light.lgts.config.system.MyMetaObjectHandler
#mybatis-plus配置 end#
---
#网关配置
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#网关配置END
---
# Redis数据库索引（默认为0）
spring:
  redis:
    database: 0
# Redis服务器地址
    host: 127.0.0.1
# Redis服务器连接端口
    port: 6379
# Redis服务器连接密码（默认为空）
    password:
# 连接超时时间（毫秒）
    timeout: 0
# 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 200
# 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
# 连接池中的最大空闲连接
      max-idle: 8
# 连接池中的最小空闲连接
      min-idle: 0
#spring-session 使用
  session:
    store-type: none


